clioncare/urls.py
from django.urls import path
from . import views

app_name = "clioncare"
urlpatterns = [
    path("", views.index, name = "index"),
    path("costpage", views.costpage, name = "costpage"),
    path("chatform", views.chatform, name = "chatform"),
    path("hairform", views.hairform, name = "hairform"),
    path("createuser", views.createuser, name = "createuser"),
    path("login", views.userlogin, name = "login"),
    path("logout", views.userlogout, name =  "logout"),
]

richproject/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = "Clion Care Admin View"
admin.site.index_title = "All right reserved"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clioncare/', include("clioncare.urls")),
]

clioncare/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField
from django.contrib.auth.models import User


# Create your models here.
class usermessage(models.Model):
    fname = models.CharField(max_length = 100)
    email = models.CharField(max_length=255)
    message = models.TextField()
    mob_no = models.IntegerField()
    def __str__(self):
        return f"{self.fname}__ message is__{self.message}!"


class patient(models.Model):
    # raw_json_data = JSONField()
    gender = models.CharField(max_length = 10)
    hair_color = models.CharField(max_length = 25)
    baldness_pattern = models.CharField(max_length = 50)
    had_transplant = models.CharField(max_length = 30)
    problem_since = models.CharField(max_length = 20)
    how_bad = models.CharField(max_length = 50)
    urgency = models.CharField(max_length = 60)
    fullname = models.CharField(max_length = 80)
    age = models.IntegerField()
    email =models.CharField(max_length=255,unique=True)
    mob_no = models.CharField(max_length = 11)
    profile_image = models.ImageField(upload_to='media/images', default="")


    def __str__(self):
        return f"{self.fullname}__{self.mob_no}__{self.email}"

class add_offer(models.Model):
    is_active = models.BooleanField(default = False)
    background_color = models.CharField(max_length = 30)
    background_image = models.ImageField(upload_to='media/images', default="")
    offer_age = models.IntegerField()
    font_family = models.CharField(max_length = 40)
    title = models.CharField(max_length = 150)
    is_right_header = models.BooleanField(default = False)
    right_header = models.CharField(max_length = 100)
    is_left_header = models.BooleanField(default = False)
    left_header = models.CharField(max_length = 100)
    is_right_content = models.BooleanField(default = False)
    right_content = models.TextField()
    is_left_content = models.BooleanField(default = False)
    left_content = models.TextField()
    offer_button_color = models.CharField(max_length = 10)
    offer_button_innertext = models.CharField(max_length = 30)


    def __str__(self):
        return f"offer: {self.title}__run for__{self.offer_age} days."

clioncare/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.urls import reverse
from django.contrib import messages
from .models import usermessage, patient
import json
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def index(request):
    return render(request, "clioncare/index.html")

def costpage(request):
    return render(request, "clioncare/costpage.html")

def chatform(request):
    if request.method == "POST":
        fname = request.POST["fullname"]
        email = request.POST["email"]
        message = request.POST["message"]
        mob_no = request.POST["mob_no"]
        newchatdata = usermessage.objects.create(fname=fname,email=email,message=message,mob_no=mob_no)
        try:
            newchatdata.save()
            messages.success(request, "Your form was submited sucessfully!, Mr Vikas will contact you within 2-3 hrs Thank You.")
            return render(request, "clioncare/index.html")
        except Exception as e:
            messages.error(request, "You entered invalid data,please retry!")
            return render(request, "clioncare/index.html")

    else:
        messages.info(request, "enter some data in the form below first,then submit")
        return render(request, "clioncare/index.html")
@csrf_exempt
def hairform(request):
    # if post method
    # if request.is_ajax():---------->>what is this???
    if request.method == "POST":
        raw_data = json.loads(request.body)
        print(raw_data)
        raw_json_data = json.dumps(raw_data)
        gender = raw_data["gender"]
        hair_color = raw_data["hair_color"]
        baldness_pattern = raw_data["baldness_pattern"]
        had_transplant = raw_data["had_transplant"]
        problem_since = raw_data["problem_since"]
        how_bad = raw_data["how_bad"]
        urgency = raw_data["urgency"]
        fullname = raw_data["fname"]
        age = int(raw_data["age"])
        email = str(raw_data["email"])
        mob_no = raw_data["mob_no"]
        print(type(request.body))
        new_patient = patient.objects.create(
                                                # raw_json_data = raw_json_data,
                                                gender=gender,
                                                hair_color = hair_color,
                                                baldness_pattern = baldness_pattern,
                                                had_transplant = had_transplant,
                                                problem_since = problem_since,
                                                how_bad = how_bad,
                                                urgency = urgency,
                                                fullname = fullname,
                                                age = age,
                                                email = email,
                                                mob_no = mob_no)
        new_patient.save()
        messages.success(request, "Your data was send to our Expert doctors, after analysing it,we will contact you, Have a nice day!")
        return redirect(reverse("clioncare:index"))
        print("in success")
        # except Exception as e:
        #     print("in failed")
        #     messages.error(request, "Your data was not send,some error occured please inform us by clicking on Q&A button on bottom right of screen!")
        #     return render(request, "clioncare/index.html")


        # # if get method
        # return redirect(request, "clioncare/hairform.html")

    # if get method
    else:
        return render(request,"clioncare/hairform.html")

@csrf_exempt
def createuser(request):
    if request.method == "POST":
        username = request.POST["username"]
        fname = request.POST["fname"]
        lname = request.POST["lname"]
        email = request.POST["email"]
        password = request.POST.get("pass")
        re_pass = request.POST.get("re-pass")
        if User.objects.filter(username = username).exists():
            messages.error(request, 'This username = ' + f"{username}" + ' already exists please choose another one!')
            return render(request,"clioncare/createuser.html")
        else:
            new_user = User.objects.create_user(username,email,password)
            new_user.first_name = fname;
            new_user.last_name = lname;
            new_user.save()
            messages.success(request, 'your account was created sucessfully with'+ f" username : {username}")
            return render(request,"clioncare/login.html")
        # else:
        #     messages.error(request, "Passwords did not matach, please re-enter password carefully!")
        #     return render(request,"clioncare/createuser.html")
    else:
        return render(request, "clioncare/createuser.html")



def userlogin(request):
    if request.method == "POST":
        loginusername = request.POST["username"]
        loginpassword = request.POST["your_pass"]
        user = authenticate(username = loginusername,password = loginpassword)
        if user is not None:
            login(request, user)
            messages.info(request,"You are now LoggedIn.")
            return redirect("clioncare:costpage")
        else:
            messages.error(request,"Error: Invalid username or password, please retry")
            return render(request,"clioncare/login.html")
    else:
        return render(request, "clioncare/login.html")

def userlogout(request):
    if request.method =="GET":
        logout(request)
        messages.info(request, "Successfully logged out.")
        return redirect("clioncare:costpage")

clioncare/templates/clioncare/costpage.html
{% extends "clioncare/layout.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href={% static "clioncare/css/costpage.css" %}>
{% endblock %}
{% block body %}



<div class="container-fluid page_container">
        <div class="container-fluid page_heading">
          <h1 style="color:white;"><strong>🎉 Welcome! To Clion Care Hair Analysis™</strong></h1>
        </div>
        <div class="row">
          <div class="col-lg-8 left_section">
            <div class="left_section_heading">
              <h3>
                  We,Are The First And Only One In Ahemdabadh To Provide Our Coustomers Advance Hair Analysis™ online,
                  Free Of Cost But For Limited Period Of Time So Take Full Advantage Of This.
              </h3>
            </div>
            <div class="left_section_content">
              <h2>Below Are Some Frequently Asked Question(FAQs)</h2>
              <hr>
              <div class="faq_questions">
                <div class="the_question_div">
                  <button data-toggle="collapse" data-target="#question1" class="btn btn-outline-primary">What Is This Hair Analysis??</button>
                  <div class="collapse" id="question1">
                    <p>In challenging times like these where world is standing still clion care, is comited to satisfy it's coustomers need, this hair analysis is just another stepping stone in that direction now by using advanced webapp, With just few clicks you can get free qoute from our expert while sitting safe in home.</p>
                  </div>

                </div>
                <div class="the_question_div" >
                  <button data-toggle="collapse" data-target="#question2" class="btn btn-outline-primary">Why I Have To Do Online Hair<br> Analysis To Get Cost Estimate??</button>
                  <div class="collapse" id = "question2">
                    <p>Hair transplant is a process which differ from person to person as according to their needs and current hair loss condition,the cost depends upon number of grafts Transplanted to the patient which depends upon how bad the hair loss, so before sending you a cost estimate it is must for our experts to know your hair condition properly, and hence this hair analysis is very important to take to get proper cost estimate. </p>
                  </div>
                </div>
                <div class="the_question_div">
                  <button data-toggle="collapse" data-target="#question3" class="btn btn-outline-primary">On What Things Cost Depend Upon??</button>
                  <div class="collapse" id = "question3">
                    <p>Cost of hair trans plant depends upon the number of grafts(hiar roots) transplanted to your head and on some extra precautionary measures which can me must for one patient but absolutely necassary for another depending upon the skin senstivity.</p>
                  </div>
                </div>

              </div>
            </div>
          </div>
          <div class="col-lg-3 welcome_image_div">
            <img src={% static "clioncare/images/welcome3.png" %} alt="welcome image">
          </div>
        </div>
      </div>

      <div class="container-fluid page_2_parent">
        <div class="container-fluid page_2_heading">
          <h1>Getting Online Consultation Is Easy As Never Before!</h1>
          <h4>See The Video Below, Showing How To Take OurFree Consultation.</h4>
        </div>
        <div class="container-fluid">
          <div class="video_cont">
            <img src = {% static "clioncare/images/videogif.gif" %}></img>
          </div>
          <h3 class = "my-5"><b>You are Just one click away from getting your hair back, Click now...</b></h3>
          <a href="{% url "clioncare:hairform" %}" class = "btn btn-large btn-warning" style = "padding:0.2rem 6rem; margin: 1rem 0 8rem 0;">Take Hair Analysis</a>
        </div>
      </div>


    <div class="">

    </div>

      <!-- <div class="cost_head_cont">
        <div class="cost_welcome">
          <h1>Welcome, To Clion Care Free Advance Hair Analysis™</h1>
        </div>
        <div class="row" style = "margin:0">
          <div class="col-lg-8 cost_left">
            <div class="container-fluid clion_msg" style="text-align:left;">
              <h4>
                  We,Are The First And Only One In Ahemdabadh To Provide Our Coustomers Advance Hair Analysis™ online,
                  Free Of Cost But For Limited Period Of Time So Take Full Advantage Of This.
              </h4>
            </div>
            <div class="reason_section">

              <div class="reason_section_header">
                <h3>Factors Affecting The Cost Of Transplantation</h3>
              </div>
              <div class="reasons">
                <ol>
                  <li>Condition of hair loss in a patient.</li>
                  <li>Types of techniques opted for.</li>
                  <li>Number of grafts used.</li>
                  <li>Area of the transplantation.</li>
                  <li> Extra care or irregularities if occur.</li>

                </ol>
              </div>
            </div> -->

            <!-- <div class="cost_faq">


              <div class="faq_question">
                <button data-toggle = "collapse" data-target=".answer1" class="btn btn-outline-primary"><h5>Why I Have To Do Online Hair Analysis To Get Cost Estimate??</h5></button>
                <div class="answer1 collapse">
                  <p>Nowadays it is a 100% painless procedure, subjected to the local anaesthesia, And if it is being done at the right clinic and by the right doctor.</p>
                </div>
              </div>

              <div class="faq_question">
                <button  data-toggle = "collapse" data-target=".answer2" class="btn btn-outline-primary"><h5>What Is This Hair Analysis??</h5></button>
                <div class="answer2 collapse">
                  <p>Transplanted hair remains forever the life if transferred from the safe donor area.</p>
                </div>
              </div>

              <div class="faq_question">
                <button  data-toggle = "collapse" class="btn btn-outline-primary"data-target=".answer3"><h5>On What Things Cost Depend Upon??</h5></button>
                <div class="answer3 collapse">
                  <p>Hair Transplant is a surgery that involves only the skin of the scalp. It doesn’t go below the skin or come in contact with any part of the brain.</p>
                </div>
              </div>
            </div> -->

          <!-- </div>
          <div class="col-lg-4 welcome_poster">
            <img src="../images/welcome3.png" alt="welcome_poster">
          </div>
        </div>
      </div> -->



      <!-- parent container -->
    </div>




{% endblock %}
{% block js %}
<script src={% static "clioncare/js/costpage.js" %} charset="utf-8"></script>
{% endblock %}

clioncare/templates/clioncare/createuser.html
{% extends "clioncare/layout.html" %}
{% load static %}
{% block title %}
<title>Create user</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href={% static "clioncare/css/createuser.css"%}>
{% endblock css%}

{% block body %}
<div class="main">

        <!-- Sign up form -->
        <section class="signup">
            <div class="container">
                <div class="signup-content">
                    <div class="signup-form">
                        <h2 class="form-title">Create account</h2>
                        <form method="POST" class="register-form" action="/clioncare/createuser" id="register-form">
                          {% csrf_token %}
                          <div class="form-group">
                              <label for="username"><i class="zmdi zmdi-account material-icons-name"></i></label>
                              <input type="text" name="username" id="username" placeholder="Create userName" required/>
                          </div>
                            <div class="form-group">
                                <label for="fname"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="fname" id="fname" placeholder="First Name" required/>
                            </div>
                            <div class="form-group">
                                <label for="lname"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="lname" id="lname" placeholder="Last Name (surname)" required/>
                            </div>
                            <div class="form-group">
                                <label for="email"><i class="zmdi zmdi-email"></i></label>
                                <input type="email" name="email" id="email" placeholder="Your Email" required/>
                            </div>
                            <div class="form-group">
                                <label for="pass1"><i class="zmdi zmdi-lock"></i></label>
                                <input type="password" name="pass1" id="pass1" placeholder="Password" required/>
                            </div>
                            <div class="form-group">
                                <label for="re-pass"><i class="zmdi zmdi-lock-outline"></i></label>
                                <input type="password"  name="re_pass" id="re_pass" placeholder="Repeat your password" required/>
                            </div>
                            <div class="form-group">
                                <input type="checkbox" name="agree-term" id="agree-term" class="agree-term" />
                                <label for="agree-term" class="label-agree-term"><span><span></span></span>I agree all statements in  <a href="#" class="term-service">Terms of service</a></label>
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                            </div>
                        </form>
                    </div>
                    <div class="signup-image">
                        <figure><img src={% static "clioncare/images/signup-image.jpg" %} alt="sing up image"></figure>
                        <a href={% url "clioncare:login" %} class="signup-image-link btn btn-outline-primary">I am already member</a>
                        <a class="btn btn-small mt-3" id="pass_btn">yoyo</a>
                    </div>
                </div>
            </div>
        </section>


    </div>
{% endblock body %}
{% block js %}
    <script src={% static "clioncare/js/main.js" %}></script>
{% endblock %}

clioncare/templates/clioncare/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    {% block title %}
    {% endblock %}

    <link href="https://fonts.googleapis.com/css?family=Montserrat|Ubuntu" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <link rel="stylesheet" href={% static "clioncare/css/layout_styles.css" %}>
    {% block css %}
    {% endblock %}
  </head>
  <body>

    <div class="container-fluid cont-1" id = "home_redirect">

      <!-- NAVBAR ------------------------------------------------->
      <nav class="navbar navbar-expand-lg fixed-top navbar-light ">
        <a class="navbar-brand" href="https://clioncare.com/"><img src={% static "clioncare/images/Logo_CLION.png" %} alt="clion_logo"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="http://127.0.0.1:8000/clioncare/#home_redirect">Home<span class="sr-only">(current)</span></a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown_1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                welcome, {{ request.user }}
              </a>
              <div class="dropdown-menu bg-light" aria-labelledby="navbarDropdown_1">
                <a class="dropdown-item" href={% url "clioncare:logout" %}>Logout</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">{{ request.user }} Profile</a>
              </div>
            </li>
            {% else %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown_1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Accounts
              </a>
              <div class="dropdown-menu bg-light" aria-labelledby="navbarDropdown_1">
                <a class="dropdown-item" href={% url "clioncare:createuser" %}>Create Account</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href={% url "clioncare:login" %}>Login</a>
              </div>
            </li>

            {% endif%}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown_2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Hair Translant
              </a>
              <div class="dropdown-menu bg-light" aria-labelledby="navbarDropdown_2">
                <a class="dropdown-item btn" href="#">About Hair Translant</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Methods Of Hair Transplant</a>
                <a class="dropdown-item" href="#">FUT Method</a>
                <a class="dropdown-item" href="#">FUE Method</a>
                <a class="dropdown-item" href="#">PRP Method</a>
              </div>
            </li>

            <li class="nav-item">
              <a class="nav-link free_btn1 btn btn-outline-warning" data-toggle="tooltip" title="Click, To Bring Your Hair Back!" data-placement="bottom" href="{% url "clioncare:costpage" %}" style="color:black;">Free Consultation</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="http://127.0.0.1:8000/clioncare/#contact_section">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" style="color:black;" href="{% url "clioncare:costpage" %}">Cost <span style="font-family:sans-serif;color:red;font-size: 0.7em;background-color:;padding: 0 0;border-radius:3px;">New</span></a>
            </li>
          </ul>
        </div>
      </nav>

      <!-- Flash messages from django -------------------------------->
      {% if messages %}
      <div class="alert alert-success alert-dismissible fade show django_alert" role="alert">
          {% for message in messages %}
          {{ message }}
          {% endfor %}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      </div>
      {% endif %}


      {% block body%}

      {% endblock %}

      <!-- popup form -->
    <a class="open-button" onclick="openForm()"><img src={% static "clioncare/images/question.png" %} alt=""> </a>
    <div class="form-popup" id="myForm">
      <form action="/clioncare/chatform" method="post" class="form-container">
        <h4>Leave Us A Message!</h4>
        {% csrf_token %}
        <label for="email"><b>Email</b></label>
        <input type="email" placeholder="Enter Email" name="email" required>

        <label for="fullname"><b>Full Name</b></label>
        <input type="text" placeholder="Full Name" id = "fullname" name="fullname" required>

        <label for="mob_no"><b>Mobile Number</b></label>
        <input type="number" placeholder="Mobile Number" id = "mob_no" name="mob_no" required>

        <label for="message"><b>Your Message</b></label>
        <textarea name="message" id = "message" rows="3" cols="27"></textarea>

        <button type="submit" class="btno btn btn-success">Submit</button>
        <button type="button" class="btno btn btn-outline-danger" onclick="closeForm()">Close</button>
      </form>
    </div>

    <!-- TOOLTIP SCRIPT -->
    <script>
      $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
      });
    </script>

    <!-- POPUP script -->
    <script>
      function openForm() {
        document.getElementById("myForm").style.bottom = "20px";
      }

      function closeForm() {
        document.getElementById("myForm").style.bottom = "-650px";
      }
    </script>

    <!-- COLLAPEABLE script -->
    <script>
      var coll = document.getElementsByClassName("collapsible");
      var i;

      for (i = 0; i < coll.length; i++) {
        coll[i].addEventListener("click", function() {
          this.classList.toggle("active");
          var content = this.nextElementSibling;
          if (content.style.maxHeight){
            content.style.maxHeight = null;
          } else {
            content.style.maxHeight = content.scrollHeight + "px";
          }
        });
      }
    </script>


    <!-- HTML DOCUMENT BACKBONE SCRIPT  -->
    <script src={% static "clioncare/js/layout_js.js" %} charset="utf-8"></script>
    {% block js %}
    {% endblock %}
  </body>
</html>

clioncare/templates/clioncare/login.html
{% extends "clioncare/layout.html" %}
{% load static %}
{% block title %}
<title>login</title>
{% endblock %}
{% block css %}
<link rel="stylesheet" href={% static "clioncare/css/createuser.css" %}>
{% endblock css%}

{% block body %}
<div class="main">

        <!-- Sing in  Form -->
        <section class="sign-in">
            <div class="container">
                <div class="signin-content">
                    <div class="signin-image">
                        <figure><img src={% static "clioncare/images/signin-image.jpg" %} alt="sing up image"></figure>
                        <a href="#" class="signup-image-link">Create an account</a>
                    </div>

                    <div class="signin-form">
                        <h2 class="form-title">Sign up</h2>
                        <form method="POST" action="/clioncare/login" class="register-form" id="login-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="username"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="username" id="username" placeholder="userName" required/>
                            </div>
                            <!-- <div class="form-group">
                                <label for="your_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="your_name" id="your_name" placeholder="Your Name"/>
                            </div> -->
                            <div class="form-group">
                                <label for="your_pass"><i class="zmdi zmdi-lock"></i></label>
                                <input type="password" name="your_pass" id="your_pass" placeholder="Password" required/>
                            </div>

                            <div class="form-group form-button">
                                <input type="submit" value="Log in"/>
                            </div>
                        </form>
                        <!-- <div class="social-login">
                            <span class="social-label">Or login with</span>
                            <ul class="socials">
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a></li>
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-twitter"></i></a></li>
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a></li>
                            </ul>
                        </div> -->
                    </div>
                </div>
            </div>
        </section>

    </div>

{% endblock %}
{% block js %}
<script src={% static "clioncare/js/main.js" %}></script>

{% endblock js %}